server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    jdbc-url: jdbc:h2:file:~/oauth2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none